theme: jekyll-theme-minimal
title: Hendrix's Portafolio
description: My research focuses on regional development, spatial econometrics, satellite data, the Sustainable Development Index, and machine learning.
